
name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for release'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: creates output
        run:  sh ./create_release.sh ${{ github.event.inputs.version }}
      - name: troubleshoot version
        run:  echo "Version ${{ github.event.inputs.version }}"

